// Generated by CoffeeScript 1.6.2
(function() {
  jQuery('document').ready(function($) {
    $('.gameover').hide();
    $('.gameend').hide();
    if (localStorage.highscore) {
      jQuery('.highscore').html(localStorage.highscore);
    }
    $('.start').click(function() {
      $('.menu').hide("drop", {
        direction: "left"
      }, "slow", function() {
        return ig.main('#canvas', GritsEvasion, 60, window.innerWidth, window.innerHeight, 1);
      });
      return $('.hud').show();
    });
    $('.pause').click(function() {
      return ig.game.resumeGame();
    });
    $('.back2menu').click(function() {
      $('.gameover').hide("drop", {
        direction: "left"
      }, "slow");
      return $('.menu').show("drop", {
        direction: "left"
      }, "slow");
    });
    return $(window).resize(function() {
      if (ig.system) {
        return ig.system.resize(window.innerWidth, window.innerHeight);
      }
    });
  });

}).call(this);
