application: grits-evasion
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /lib
  static_dir: lib
- url: /lib/*
  static_dir: lib/*
- url: /media
  static_dir: media
- url: /tools
  static_dir: tools
- url: /img
  static_dir: img
- url: /sound
  static_dir: sound

- url: /404.html
  static_files: 404.html
  upload: 404.html

- url: /.*
  script: mainHandler.app