// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  ig.module('game.entities.explosion').requires('impact.entity').defines(function() {
    return _this.EntityExplosion = ig.Entity.extend({
      size: {
        x: 84,
        y: 80
      },
      animSheet: new ig.AnimationSheet('media/explosion.png', 84, 80),
      sound: new ig.Sound('sound/explode0.ogg'),
      init: function(x, y, settings) {
        if (settings.angle) {
          this.angle = settings.angle;
        }
        this.parent(x, y, settings);
        this.addAnim('explosion', 0.1, [0, 1, 2, 2, 2]);
        this.sound.volume = 0.2;
        return this.sound.play();
      },
      update: function() {
        if (this.currentAnim.frame === 4) {
          this.kill();
        }
        return this.parent();
      }
    });
  });

}).call(this);
