// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  ig.module('game.entities.healthbar').requires('impact.game', 'impact.entity', 'impact.background-map').defines(function() {
    return _this.EntityHealthbar = ig.Entity.extend({
      size: {
        x: 210,
        y: 210
      },
      animSheet: new ig.AnimationSheet('media/HealthBar.png', 32, 5),
      Unit: 0,
      init: function(x, y, settings) {
        this.addAnim('Full', 1, [0]);
        this.addAnim('Ninety', 1, [1]);
        this.addAnim('Eighty', 5, [2]);
        this.addAnim('Seventy', 1, [3]);
        this.addAnim('Sixty', 1, [4]);
        this.addAnim('Fifty', 1, [5]);
        this.addAnim('Fourty', 1, [6]);
        this.addAnim('Thirty', 1, [7]);
        this.addAnim('Twenty', 1, [8]);
        this.addAnim('Ten', 1, [9]);
        this.addAnim('NearDeath', 1, [10]);
        this.parent(x, y, settings);
        return this.zIndex = 6;
      },
      update: function() {
        this.pos.x = this.Unit.pos.x;
        this.pos.y = this.Unit.pos.y;
        if (this.Unit.health === this.Unit.MaxHealth) {
          return this.currentAnim = this.anims.Full;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .9) && this.Unit.health < this.Unit.MaxHealth) {
          return this.currentAnim = this.anims.Ninety;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .8) && this.Unit.health < (this.Unit.MaxHealth * .9)) {
          return this.currentAnim = this.anims.Eighty;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .7) && this.Unit.health < (this.Unit.MaxHealth * .8)) {
          return this.currentAnim = this.anims.Seventy;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .6) && this.Unit.health < (this.Unit.MaxHealth * .7)) {
          return this.currentAnim = this.anims.Sixty;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .5) && this.Unit.health < (this.Unit.MaxHealth * .6)) {
          return this.currentAnim = this.anims.Fifty;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .4) && this.Unit.health < (this.Unit.MaxHealth * .5)) {
          return this.currentAnim = this.anims.Fourty;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .3) && this.Unit.health < (this.Unit.MaxHealth * .4)) {
          return this.currentAnim = this.anims.Thirty;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .2) && this.Unit.health < (this.Unit.MaxHealth * .3)) {
          return this.currentAnim = this.anims.Twenty;
        } else if (this.Unit.health >= (this.Unit.MaxHealth * .1) && this.Unit.health < (this.Unit.MaxHealth * .2)) {
          return this.currentAnim = this.anims.Ten;
        } else if (this.Unit.health > 0 && this.Unit.health < (this.Unit.MaxHealth * .1)) {
          return this.currentAnim = this.anims.NearDeath;
        } else if (this.Unit.health <= 0) {
          return this.kill();
        }
      }
    });
  });

}).call(this);
